language: c

compiler: gcc

cache: ccache

os: linux

dist: boinic

#The COVERITY_SCAN_BRANCH environment variable will be set to 1 when the Coverity Scan addon is in operation.
script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./configure && make ; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "knodI9TajfFYHQxFISYnb3voYQ+cvv1pPzfZa0+9MPY45iKB4L9xuZFNi6aZuhOUFR+OiEkohVMXn3z7U9GfH63sUgTStX2zMoZ3MmyV/SakXuWAvBMnB61oBLZX0bIDs2bFdykZ1jCCmGSSGSRtKRqspvsqI1DbAwGkJ25i3sUMz6Zw9WP3zsVExg3CP7E8JZCCa++YE9wsbZbXi2G7ccxmj3O1bBoFtfSnoAtm5kNGkVRVP9ebNrAKMCOls81uv549iLnhzzc6MtHXZ5WyO+CXQD8HrKMZ3gTRNfa6UGu94M2nyVzSZKeCRQniN3VHcuSrS9xmwnbh8/YydN1qmSEn4WCYVAQ6twOrxjdJWYNdl6uQYgeLisIx0E57U6yqZ2s6tecsjPqus7sU8P30Gxf1Ebq/bpToi3ZOGX5+A1wddU/51ET3gdGnhj1HO/lLv9ugX2lysabXCJPjZJXSu34Hy9gtCGMFBV5oxMF8tEWrEx+KGT/KnOo4lNQCCCkMZFiJ1BepAiKN/XHmtfvVBssEdSrvJ0ErcwpQMqMqk0fJOuOLdgEF4hi7EQmGVPl4Y0xk2oK3yuWskMNkAXkW+1pCfeeEFej4vFQGEel0fH003cyj/+aPqFadm0J5EghR5T6Qhpve8Knw751ZXXKCUBPdF9Ecu+Ej09PEJSkfFjU="


before_install:
  - sudo apt-get -y install libprocps-dev
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
    apt:
       update: true
    coverity_scan:
       project:
         name: "rjaan/procps_ptree"
         description: "procps_ptree - shows inforamtion of executed process and task"
       notification_email: rjaan@yandex.ru
       build_command_prepend: "./configure"
       build_command: "make"
       branch_pattern: coverity_scan

#eof
