language: c

compiler: gcc

cache: ccache

os: linux

dist: boinic

#The COVERITY_SCAN_BRANCH environment variable will be set to 1 when the Coverity Scan addon is in operation.
script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./configure && make ; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "WaDrV+pNkBAKFR/kZfuz963Y1oN+oXRkk9NRKCUFSpptgAJi9tqyGzUvtbxTvr88XH3YA8rkJGKXAYeghq/DDUxicmEpKlIOlxtIUscRXBPA8anFK7abYsqQK8iLtV8fMt/gc6zbbnDX9qjTDH7gVE1Qn/51e1sVSlATrq/yIKDy6HU6NNU/RaU0ewbjKDdUO+81k7hLMF21jK//Qwj3CBi23txVzo42VQm3BUNCNRG5of13JVAHNfJQUxiSXGeR6erFnmYpTIoxCYlt1cYRfjlNlEATKhcmsxn0QRJrG3TtTxtqtU+xe4Jk+zcspJQi9oHg/nG4vcAltA0D0SgQiWCz7BrOEiXHcaDJImH/To6rd2M2IzCUSPCdvpfxcEuZJOh1Lxq926YVjbQrlP1O49BVzttXuBjhYTbAJYGSjUTBLETMpTvH+ZHDwW+bWMp744+py6NFzHqhc+YLuD6KHSkjkq55BeDRU9+aEY3QcaTpHKBqjWaIfaIn96rFP5SQDVAATRpOlaufLRqynDtScCCRKG6WhUtb1boEWNgTDAkCqhci4jZXtMfRip8LlsjZeDrI1J5KI6+ol/FXNN/XmZ9ghLbfQrfM1Ut27GoPWM1+WH/Z7k8plf3OmxQPrttqDpLldVuWAWITdik/7CU6rKii9cMAwiF18HF9o1exj8U="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo apt-get -y install libprocps-dev

addons:
    apt:
       update: true
    coverity_scan:
       project:
         name: "rjaan/procps_ptree"
         description: "procps_ptree - shows inforamtion of executed process and task"
       notification_email: rjaan@yandex.ru
       build_command_prepend: "./configure"
       build_command: "make"
       branch_pattern: coverity_scan

#eof
