language: c

compiler: gcc

cache: ccache

os: linux

dist: boinic

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "d3sjcams1F6ex1Kv5My6cOSC4Gtd1i9RuoAbdoLbNnL9GwFbMmHddOwoZMCadr6VrgbIDcgMd2Jgqogr3eONV9JHsOFrlUklvxlWxkMnsMzzCquITKB8pCYj3lzriy9PuP/jkuSA0+nwTFPpUFyKuraXKNH+sLOSSBAgDsBtoQRuRxeMiWiRDhHb75qP0uhRL8Sl3PqLh5ZW9ZUrdIgckTE1AAc4wMvVpDn9Yujv9JQVi+PEV7q8KUzF+1t+oM88c+IrpHipV/EjOeqbzYhD1AoyfKvI+s3Ix8O6FQST/zYBF5oOvIFzrJcvD5+0Il/KHlZxDzjO+TR18ynZ3iKD37eytwZ/r9RG5U1wygu3Ihgaug4a4X0iqOD35FEs4TQ6AyPciT2AI1AzNU8SPQGNdtRnB2wPijcIY8yQNzNu8UBWHGxm/1zT5Ug2QVLBptG8OW6nJowczcyFyv+FGY0DyvVqU7JqWQb2P64YO5oSamFADpYggXZOssI9DqXeiDp5h+iwspyQCrz2hT0vyn5LibTdYQ2OVjl0rs+dmk5fg5Jq0UYfOaFqwi9PeTzbC/aKft4PHyCIto1BBmZsrwhdh91TDOfpq/rkrUPY1/IhdPMyWnsNgc8uIBky70NlszsaxjIY7YMVjoNwn21+gbDzuNjCUJoc9UEy0BZnY02JLRI="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo apt-get -y install libprocps-dev

addons:
  coverity_scan:
    project:
      name: "rjaan/procps_ptree"
      description: "procps_ptree - shows inforamtion of executed process and task"
    notification_email: rjaan@yandex.ru
    build_command_prepend: "./configure"
    build_command: "make"
    branch_pattern: coverity_scan
