language: c

compiler: gcc

cache: ccache

os: linux

dist: boinic

#The COVERITY_SCAN_BRANCH environment variable will be set to 1 when the Coverity Scan addon is in operation.
script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./configure && make ; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "K+pVLjGHBWS0oVjstybo5Pok3S8QVI3Um6BC4Ao+S5aMbZJRLkLIfJTgzGLnyR0Hfqpcr+dQDWEcueLLSgCiYpdp9O66p+/VKBPsRwykMq1sAq59VXDuXUhFnwDr3wY4gBJMv+yWXtOZ/Jvy3uTHqnekMDYJwFnWhjDtpNeeBrk0Oczar7r5a0HIIp2gucJ6i9FpCYQRBOnmg8NezdfuuDKX5GqpMwRou21k5mxbg9hQpZPjHfLccrF+9V1cfpbWYoUmPAwITrz5kBUYeCUrTzcp0FhYyChfZnCbnHw4b6vK6fFx2L3JXvlg/tbqNX3U+h1ObMYUi2REm3CCY07aypGO/oFOi1dcmDjIh5Cjn3DRkEEf95EsGCiEa58UyILFJnfH92D3SvYLEOhGmcqwebNW9DhsRTQmpnuRtA5aHTNJE+rAmmwMWBH4HtTbsmofIAbWL3urCGQHTwt2s9D7J3aKxS1EXcLZKWnR+1aiLAOtZ7JJ68bXNuvcFf2CznUCBPW6fG9nAGYJlxlL0S6iqbwFu4K3AJIUEPEangyA4Qz4fa08JiInkX51SDmLXJSeGnT8/E/J9w1ZM7pqC4dGh2kooaQ67QfHYf0YrGbD0+UOiJbjisYkK+enmLT6FpHgJ4orNVCx81ru/xamkokyo03WYqkheFSQs/fA4m4+Jsw="

before_install:
  - sudo apt-get -y install libprocps-dev
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
    apt:
       update: true
    coverity_scan:
       project:
         name: "rjaan/procps_ptree"
         description: "procps_ptree - shows inforamtion of executed process and task"
       notification_email: rjaan@yandex.ru
       build_command_prepend: "./configure"
       build_command: "make"
       branch_pattern: coverity_scan

#eof
