language: c

compiler: gcc

cache: ccache

os: linux

dist: boinic

#The COVERITY_SCAN_BRANCH environment variable will be set to 1 when the Coverity Scan addon is in operation.
script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./configure && make ; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "sySIFENlHZgsFQM+ntG1V8FR9yvm+Bv2/Z1tlaELbtyX1jUcywLQ/DuV0+5234qvPXVW2sCM6gZifIfPt/WH7gP2Dm6bEx5GHYZ89zrGK78GWLL7gjnbn2tKQwVOGYcfmRxgP/1llvgHTt5JqMzQcjUvH4QUWQ32XMQ9iz0nKM4nrpaEWd8nWZzPvz1TgC/yy9A+fZtULiXUk09MkEGfJXUbl9i89i08jeHaKQlfMg+jHdvfP7VZ+kibxWHPqDQXH4D6c9JjEx9J/i274988UMUmhNChL5F9NdDPt7jUpUkDqhBtnRbF6CK4dlB8DBE72/YqipTZGm+QLBeOYApsMzhF5GfloVcByfE4GWq7C7Dx8yQYY9okIjfp0t/Tn51WymeiTTnyQAErYRBWstIzwhZ70AZ8sm/+7t3bTpttygMIOLdvLKNeBpzxDdIJSv4UT8Zos+TG/ls+QlEwKqzNCz32IfzEAvAsJqsZ30xaIgckIXj5r0dxN9+dXGz9rapXVt6dkrBCxC5vpk8FmASgZrnRMdB+l5A9jD05tF5IlCreKGDQOD90rjK8I7MJJX93WL/2l+IzYAi1+darO/PppgezzCLhj9CKJek52t3gC6YuWrI6u3C1YKJJwU+W20lY5z8/o8tLjY2BCnRgqvpR2GX06eYBmtCRvfpg4pHrW54="

before_install:
  - sudo apt-get -y install libprocps-dev
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
    apt:
       update: true
    coverity_scan:
       project:
         name: "rjaan/procps_ptree"
         description: "procps_ptree - shows inforamtion of executed process and task"
       notification_email: rjaan@yandex.ru
       build_command_prepend: "./configure"
       build_command: "make"
       branch_pattern: coverity_scan

#eof

