language: c

compiler: gcc

cache: ccache

os: linux

dist: boinic

#The COVERITY_SCAN_BRANCH environment variable will be set to 1 when the Coverity Scan addon is in operation.
# script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./configure && make ; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "TGaSeQhJEKSkPH+qTJOUwi5zH8K2wGtCahYxcoy/wTz8lJgsVNJt/etuwQ2BIXyGlIK6YTEMFysa1LbRhORMjdCNwqBho6Ogdl8FD9m09rInRLqxg1gE63zXQC/13SRv1zV/XRh3qsfeVopw800wXG8wjXXXuWY9liaTnqmeMX+Vl831RpYLePZraHrU39f6hIikRNe+rUsAJhOJ0sVWdpBIS59ymiejRjMDUoiohLmPeCG7pbifte3sBoJ4bVYANuoD6G+E3mnVXajzOzCD6gMUOHr9HX1P/ES20R3NvOOyqq76SZyQ9EDED3DWnZUSJrh+MDIbTlF+DZQAq5L6dWTVaEVr6fJ2xsTY2WMZhkFtOfMUqorHKs4IihOzTdYSUO0xuj46BRm7h5L571fE8EiqbrxXmPzrJ9HL/AE72BPhC8xfkiK0wAWdgocukBApobXeX7wwzIG5KygWCKxU+yVY0ah+vmKWnl8by4mJf+uzIz+lVcAWKwnjK9Lof50ntOWyE3yrrmzdDll24baVAaJpAhSkm9cTc3yc51l2ju+jLv95couM4g7vyCc/IlSgudD186LkQpntEF/kyk6uovBk9j13PY/MPXOnu/FSfCPDbRSZmOqoDCoQ+jqe1g+GYFnut1ORg+2RaMCfgggridR6Fhxtd/yogSOtbeF4IWQ="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo apt-get -y install libprocps-dev
addons:
     apt:
        update: true

addons:
  coverity_scan:
    project:
      name: "rjaan/procps_ptree"
      description: "procps_ptree - shows inforamtion of executed process and task"
    notification_email: rjaan@yandex.ru
    build_command_prepend: "./configure"
    build_command: "make"
    branch_pattern: coverity_scan    
