language: c

compiler: gcc

cache: ccache

os: linux

dist: boinic

#The COVERITY_SCAN_BRANCH environment variable will be set to 1 when the Coverity Scan addon is in operation.
script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./configure && make ; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "oAzjqCP9KIcLSTibUJYwMuoeTSXwDLd+tB0oLqtLbHOh/ZhpJCU1m5ApQ5dlNHbjZZut/h4FCqFl7u6LR1IPoZdZHT3ta8BBtFXnZIJffKcmQWkJX5SXFlsyHPg/7x7YLFub7ImngR5X21fbEZIfOrP31f+jVQ/G1LffJpCLqMLImjBhvi9PQzHQ3pC5GWHlw1+oQnh5pvODsNl6wte0z9+XkCSqd2SHOymw1iUi906wrPd8mhBEvTsVDjLxsvrnbmsKWZlb4ZAZVsgEbo2iYPp0jxT8FpeWEWLg52wbeED9YeFsvityudqRrT3pINVIoY059/QslbcISUarZrgwHEYyfLq1kKZwu2Lvaq3Uxo3dNWNImKRGyEJVBBl7CMt1rsKx4PPcbNjeAJ2dDRzoky3CHpwDwuogu62T9IfcO7BMZ1m0ez4PWp5IpPdqUso6XrHgqWvmzjIGta4wzejqZN60/aHUhbjfYFtQ1KBVW/ZAZxepNxcuUmLad4iNoILVm9KbjtTOOXOY0m7wbn2uibSaejhUQ1jG9wqco9LSIM2d54XIdt8ueLqJLsKnlyRIBXu3xGb0YQSknlqTyPVXbhgjeRX9yg7e/OGf2lrEdAhfcTcHnqntWdSAs6YoBwE2VOcYr4pjSNPJIzSxdmycXymL3987zGdjW+UXzraRvuQ="


before_install:
  - sudo apt-get -y install libprocps-dev
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
    apt:
       update: true
    coverity_scan:
       project:
         name: "rjaan/procps_ptree"
         description: "procps_ptree - shows inforamtion of executed process and task"
       notification_email: rjaan@yandex.ru
       build_command_prepend: "./configure"
       build_command: "make"
       branch_pattern: coverity_scan

#eof
